### ISSUE TITLE
1.8.0 was rejected by Chocolatey

### ISSUE THREAD

**Issue by bradfitz** [zombiezen/tailscale-chocolatey#9]
Our 1.8.0 update got rejected:

>chocolatey-ops left the following comment(s):
>
>tailscale has failed automated validation.
>
>Requirements
>Requirements represent the minimum quality of a package that is acceptable. When a package version has failed requirements, the package version requires fixing and/or response by the maintainer. Provided a Requirement has flagged correctly, it must be fixed before the package version can be approved. The exact same version should be uploaded during moderation review.
>
> The ProjectUrl element in the nuspec file should be a valid Url. Please correct this More...

I emailed the Google Group (which I can't link to yet because my message isn't moderated there, and the group is closed to linking unless you join it).

But basically I said that we do have that field and haven't updated it, so I'm not sure why it's started failing.

**Comment by legowerewolf** [comment]
I got nuthin'. The only thing I can think of is that the validator got a timeout when it checked the URL? 

Here are the validator rules concerning the ProjectUrl property:
- [Missing or empty](https://docs.chocolatey.org/en-us/community-repository/moderation/package-validator/rules/cpmr0009)
- [Matches LicenseUrl\*](https://docs.chocolatey.org/en-us/community-repository/moderation/package-validator/rules/cpmr0038)
- [Matches SourceUrl\*](https://docs.chocolatey.org/en-us/community-repository/moderation/package-validator/rules/cpmr0041)

\* These articles haven't been filled out.

**Comment by legowerewolf** [comment]
What's behind that "More..." at the end?

**Comment by legowerewolf** [comment]
This can probably be closed. It's been accepted, as of 14 May.

**Comment by bradfitz** [comment]
Yeah, they fixed it (see https://github.com/chocolatey/home/issues/50).
